version: '3'
services:
  #授权服务
  action_admin:
    container_name: action_admin
    build: # 服务的 Docker 构建文件位置
      context: ./action_admin
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 8601:8601
    networks:
      - action
    environment:
      - COMPOSE_PROJECT_NAME=action_admin
    volumes:
      - ./doc/data/log/:/logs/
      - ./doc/config/action_admin:/config/
  #网口服务
  action_gateway:
    container_name: action_gateway
    build: # 服务的 Docker 构建文件位置
      context: ./action_gateway
      dockerfile: Dockerfile-dev-dev
    restart: always
    ports:
      - 8607:8607
    networks:
      - action
    environment:
      - COMPOSE_PROJECT_NAME=action_gateway
    volumes:
      - ../log/:/logs/
      - ../config/action_gateway/:/config/
  #图片服务
  action_picture:
    container_name: action_picture
    build: # 服务的 Docker 构建文件位置
      context: ./action_picture
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 8602:8602
    networks:
      - action
    environment:
      - COMPOSE_PROJECT_NAME=action_picture
    volumes:
      - ../log/:/logs/
      - ../config/action_picture/:/config/
      - ../data/action_data/:/home/action_blog/action_data/
  #邮件服务
  action_sms:
    container_name: action_sms
    build: # 服务的 Docker 构建文件位置
      context: ./action_sms
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 8604:8604
    networks:
      - action
    environment:
      - COMPOSE_PROJECT_NAME=action_sms
    volumes:
      - ../log/:/logs/
      - ../config/action_sms/:/config/
  #前端后台服务
  action_web:
    container_name: action_web
    build: # 服务的 Docker 构建文件位置
      context: ./action_web
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 8603:8603
    networks:
      - action
    environment:
      - COMPOSE_PROJECT_NAME=action_web
    volumes:
      - ../log/:/logs/
      - ../config/action_web/:/config/
networks:
  action:
    external: true