version: '3.1'
services:
  mysql:
    image: mysql:8 # 使用的镜像
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1948614228
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - ./doc/data/mysql_data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./doc/data/mysql/init/:/docker-entrypoint-initdb.d/ # 启动脚本
    networks:
      - action
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos
    env_file:
      - doc/data/nacos/nacos-config.env
    volumes:
      - ./doc/data/log/nacos/:/home/nacos/logs
      - ./doc/data/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: always
    networks:
      - action
  redis:
    image: redis:6
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass 1948614228 --appendonly yes # 启动redis服务并添加密码为：1948614228,并开启redis持久化配置
    volumes:
      - ./doc/data/redis_data:/data
    networks:
      - action
  rabbitmq:
    image: rabbitmq:3.12.7-management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1948614228
    volumes:
      - ./doc/data/rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - action
  portainer:
    image: portainer/portainer:alpine
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./doc/data/portainer_data/data:/data
      - ./doc/data/portainer_data/public:/public
networks:
  action:
    external: true
