version: '3'
services:
  #授权服务
  action_picture:
    image: registry.cn-chengdu.aliyuncs.com/actionblog/action_picture:latest
    container_name: action_picture
    restart: always
    ports:
      - 8602:8602
    networks:
      - action
    environment:
      - COMPOSE_PROJECT_NAME=action_picture
    volumes:
      - ../log/:/logs/
      - ../config/action_picture/:/config/      
      - ../data/action_data/:/home/action_blog/action_data/
networks:
  action:
    external: true
