version: '3'
services:
  #数据服务
  action_data:
    image: nginx:1.24.0-alpine
    container_name: action_data
    restart: always
    ports:
      - 8600:8600
    networks:
      - action
    volumes:
      - ../data/action_data/:/home/action_blog/action_data/
      - ../config/action_data.conf:/etc/nginx/conf.d/default.conf
networks:
  action:
    external: true
