version: '3'
services:
  #授权服务
  mogu_data:
    image: registry.cn-chengdu.aliyuncs.com/mogublog/nginx
    container_name: action_data
    restart: always
    ports:
      - 80:80  
      - 8600:8600
    networks:
      - mogu
    volumes:
      - ../data/mogu_data/:/home/mogu_blog/mogu_data/
      - ../config/action_data.conf:/etc/nginx/conf.d/default.conf
networks:
  mogu:
    external: true
