version: '3.1'
services:
  nacos:
    image: nacos/nacos-server:1.4.1
    container_name: nacos
    env_file:
      - nacos/nacos-config.env
    volumes:
      - ../log/nacos/:/home/nacos/logs
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: always
    networks:
      - action
      
networks:
  action:
    external: true
