version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.12.7-management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1948614228
    volumes:
      - ../data/rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - action
      
networks:
  action:
    external: true
