version: '3'
services:
  #授权服务
  vue_action_admin:
    image: registry.cn-chengdu.aliyuncs.com/actionblog/vue_action_admin:latest
    container_name: vue_action_admin
    restart: always
    ports:
      - 9528:80
    networks:
      - action
    env_file:
      - ../../config/vue_action_admin.env
    environment:
      - COMPOSE_PROJECT_NAME=vue_action_admin

networks:
  action:
    external: true
