version: '3'
services:
  #授权服务
  vue_action_web:
    image: registry.cn-chengdu.aliyuncs.com/actionblog/vue_action_web:latest
    container_name: vue_action_web
    restart: always
    ports:
      - 9527:80
    networks:
      - action
    env_file:
      - ../config/vue_action_web.env
    environment:
      - COMPOSE_PROJECT_NAME=vue_action_web
networks:
  action:
    external: true
