# ============================== Filebeat inputs ===============================

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ../../../log/action-web/*.log
    fields:
      docType: action_web-log
      project: action_web
      from: action_web
    fields_under_root: true
    multiline:
      pattern: '^\[action-web:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/action-admin/*.log
    fields:
      docType: action_admin-log
      project: action_admin
      from: action_admin
    fields_under_root: true
    multiline:
      pattern: '^\[action-admin:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/action-sms/*.log
    fields:
      docType: action_sms-log
      project: action_sms
      from: action_sms
    fields_under_root: true
    multiline:
      pattern: '^\[action-sms:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/action-picture/*.log
    fields:
      docType: action_picture-log
      project: action_picture
      from: action_picture
    fields_under_root: true
    multiline:
      pattern: '^\[action-picture:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/action-gateway/*.log
    fields:
      docType: action_gateway-log
      project: action_gateway
      from: action_gateway
    fields_under_root: true
    multiline:
      pattern: '^\[action-gateway:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/action-monitor/*.log
    fields:
      docType: action_monitor-log
      project: action_monitor
      from: action_monitor
    fields_under_root: true
    multiline:
      pattern: '^\[action-monitor:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s
  - type: log
    enabled: true
    paths:
      - ../../../log/action-search/*.log
    fields:
      docType: action_search-log
      project: action_search
      from: action_search
    fields_under_root: true
    pipeline: action-log
    multiline:
      pattern: '^\[action-search:[\d\.:]+\]'
      negate: true
      match: after
      timeout: 2s


# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

# =================================== Kibana ===================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:

# ---------------------------- Elasticsearch Output ----------------------------
# output.elasticsearch:
# Array of hosts to connect to.
# hosts: ["192.168.163.128:9200"]
# bulk_max_size: 2048

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["elk:5044"]
  bulk_max_size: 2048

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~