#app
server:
  port: 8604

#阿里大于
accessKeyId: XXXXXXXXXXXXXXXXXXXXXXXXX #修改成自己的
accessKeySecret: XXXXXXXXXXXXXXXXXXXXXXXXXX #修改成自己的

#spring
spring:
  jmx:
    default-domain: action_sms
  thymeleaf:
    cache: true   #关闭缓存
  application:
    name: action-sms

  #redis
  redis:
    host: 106.55.99.240 #redis的主机ip
    port: 6379
    password: mogu2018

  #RabbitMq
  rabbitmq:
    host: 106.55.99.240 #rabbitmq的主机ip
    port: 5672
    username: admin
    password: mogu2018

  #mail
  mail:
    username: damaha666@163.com # 修改成自己的
    password: EYQZSJBFJAZVDVKM #授权码开启SMTP服务里设置，这里修改成自己的
    host: smtp.163.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: false
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8606
        username: user
        password: password123
        instance:
          service-base-url: http://localhost:8604

  # sleuth 配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
  # zipkin 配置
  zipkin:
    base-url: http://localhost:9411  # 指定了Zipkin服务器的地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always