server:
  port: 8606

spring:
  application:
    name: action-monitor
  security:
    user:
      name: user
      password: password123
  boot:
    admin:
      ui:
        title: 蘑菇博客监控中心
        brand: 蘑菇博客监控中心
      notify:
        mail:
          enabled: true
          # 服务上下线会自动发送邮件
          from: damaha666@163.com
          to: 1948614228@163.com

  #mail
  mail:
    username: damaha666@163.com  # 改成自己的
    password: EYQZSJBFJAZVDVKM #授权码开启SMTP服务里设置，改成自己的
    host: smtp.163.com

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true