spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: nacos:88483
        namespace: dev
      config:
        server-addr: nacos:88483
        #文件后缀
        file-extension: yaml
        #指定分组
        group: dev
        #指定命名空间
        namespace: dev
    # 配置Sentinel流控
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: sentinel:8070
        #默认8719端口,如果被占用会向上扫描。
        port: 8719